<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/4/24 0024
 * Time: 11:20
 */

namespace app\index\controller;
use think\Db;
//权限验证类
class Auth extends Base
{
    private $User;
    public function _initialize()
    {
        //获取登陆信息
        $this->User = $this->get_user();
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    //验证当前登录用户的权限
    public function _checkKey(){
        $access = session('access');
        if(empty($access)){
            $access = self::getUserModuleList('access');
        }

        $key = Obtain_model();
        if(!in_array($key,$access)){
            if(!$this->request->isAjax() && !$this->request->isPost()){
                self::showNotice('抱歉，你没有操作权限');
            }else{
                self::returnMessage('抱歉，你没有操作权限');
            }
        }
    }


    /**
     * 获取用户权限
     */
    protected function getUserModuleList(){
        $auths = '';
        if(isset($this->User)) {
            //获取用户信息
            $user = Db::name('user')->where('id=' . $this->User['id'])->find();
            if (!empty($user)) {
                $arrace = Db::name('rule')->where('id=' . $user['rule_id'])->find();
                if (!empty($arrace)) {
                    $auth = Db::name('auth_rule')->where('rule_id=' . $arrace['id'])->find();
                    if (!empty($auth)) {
                        //获取到角色权限信息
                        $auths = Db::name('auth')->where(array('id' => array('in', $auth['auth_id']), 'status' => '1'))->select();
                    }
                }
            }
        }
        return $auths;
    }

    public function name(){

    }

    public function addauth(){
        if($this->request->isPost()){

        }else{
            return
        }

    }



}